/control/verbose 2
/tracking/verbose 2

/geometry/source detector1.tg

/run/initialize

/geometry/test/run

/vis/open 
/vis/drawVolume


/gps/pos/type Point
/gps/pos/centre -350 0 0
/gps/direction 1 0 0

/gps/particle ion
/gps/ion 2 4 0 0
/gps/ene/type Mono
/gps/ene/mono 1 keV
/run/beamOn 10

/gps/particle e-
/gps/ene/mono 1 MeV
/run/beamOn 10

/gps/particle gamma
/gps/ene/mono 1 GeV
/run/beamOn 10

/gps/particle neutron
/gps/ene/mono 1 MeV
/run/beamOn 10

/vis/viewer/set/autoRefresh true
/vis/scene/add/axes 
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate
/run/beamOn 100
/vis/viewer/refresh