/control/verbose 2
/tracking/verbose 2

/geometry/source detector.tg

/run/initialize

/geometry/test/run

/vis/open VRML2FILE
/vis/drawVolume


/gps/particle ion
/gps/energy 1 keV
/gps/direction 1 0 0
/gps/pos/centre 0 0 -150 mm


/gps/particle e-
/gps/ene/mono 1 MeV
/run/beamOn 10

/gps/particle gamma
/gps/ene/mono 1 GeV
/run/beamOn 10

/gps/particle neutron
/gps/ene/mono 1 MeV
/run/beamOn 10

/vis/viewer/set/autoRefresh true
/vis/scene/add/axes 
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate
/run/beamOn 100
/vis/viewer/refresh