/control/verbose 
/process/em/verbose 0
/process/had/verbose 0
/tracking/verbose 0
/geometry/source detector_Ge.tg
/physics_lists/factory/addRadioactiveDecay

/run/initialize
/process/list
# /process/inactivate eIoni
# #/process/inactivate annihil 
# /process/inactivate msc


/vis/open
/vis/drawVolume
/vis/viewer/refresh
/vis/scene/add/axes
/vis/scene/add/gps
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

/gps/position -35 0 0 cm
/gps/direction 1 0 0

/gps/particle e+
/gps/energy 100 MeV
/run/beamOn 10
/vis/viewer/refresh

/vis/disable
/tracking/verbose 0
# turn on data recording
/analysis/setFileName e+_Ge_100MeV.root
# turn on progress report
/run/verbose 0
/run/printProgress 10000
# start simulation
/run/beamOn 20000



